### ISSUE TITLE
develop bulk read function

### ISSUE THREAD

**Issue by RonanHiggins** [ccatobs/MODBUS#12]
A bulk read read option would be useful to speed up the reading of modbus registers.  2 options are currently available, a single register read and an async single register read. The async version is considerable faster than the sync version particularly as the register count increases. The async version however doesn't work with some hardware (DIN rail PDU for example).

A third option for read would be read chunks of data from the modbus client. One caveat to bulk reading is that the pymodbus library is limited to 125 registers in one read. This would require the bulk read to read modbus registers that stretch over 125 registers in chunks.

**Comment by Tamburasca** [comment]
Sorry, I will focus on bulk read option if the performance of all other options will turn out unsatisfactory. Pls. note that the current development is on branch "dev" that is ahead on master.

**Comment by RonanHiggins** [comment]
development is already done, see the 12-bulk-dev branch. Since asnyc option hasn't worked with some clients we should have this 3rd option available, I don't see async working for the generators for example. Have a look at the 12-branch and see what you think, I can adapt to the dev branch, changes aren't huge and sit within your framework

**Comment by Tamburasca** [comment]
Since the MODBUS bulk reading option is an affair of your heart, I suggest you take over entire responsibility of that particular Github repo henceforth. Unfortunately, I do not have that much time for extensive MODBUS activities besides my other work packages. In particular, I do not envision a strong reason why we should spend additional time on a development that may not be required at all. This said, we have not even defined a tolerable time yet that the one-step-ahead sync reader must not exceed.

**Comment by RonanHiggins** [comment]
I think there is a need for this bulk_read function, okay Ralf I will take over responsibility for modbus, this makes sense as I'm closer to the hardware. that said Ralf, the library is in good shape and doesn't require much updates..

**Comment by Tamburasca** [comment]
Fine with me! I'll retreat from any MODBUS activities then. Please take also care of rest ...
